kabin:
  source:
    path: /Java/file/
    filename:
      map:
        adyen: adyen.txt
        ebanx: ebanx.xlsx
        emis: first.CSV,second.CSV
      list:
        - 1
        - 2
server:
  port: 8080

#  健康检查配置
management:
  endpoint:
    health:
      enabled: true
      show-details: always
#debug: true
